FROM centos

RUN yum install python3 -y

RUN pip3 install --upgrade pip

RUN pip3 install keras

RUN pip3 install tensorflow

RUN pip3 install numpy 

RUN pip3 install pandas

RUN pip3 install scipy

RUN pip3 install opencv-python

RUN pip3 install sklearn 
